engines:
  duplication:
    enabled: false
    config:
      languages: -javascript
  eslint:
    enabled: true
    config:
    extensions:
      - .es6
      - .js
    checks:
      similar-code:
        enabled: false
exclude_sparherns:
  - 'node_modules/'
  - '.nyc_output'
  - 'coverage'
  - './*.test.js'
